2024-04-04 14:46:40,311: root: INFO: MLTrader : Executing the initialize lifecycle method
2024-04-04 14:46:41,653: root: INFO: Current backtesting datetime 2023-12-15 08:30:00-05:00
2024-04-04 14:46:41,654: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-04-04 14:46:41,655: root: INFO: Current backtesting datetime 2023-12-15 09:30:00-05:00
2024-04-04 14:46:41,655: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-04-04 14:46:41,657: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-04-04 14:46:41[0m
2024-04-04 14:46:41,657: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'order_type'
2024-04-04 14:46:41,657: root: ERROR: Traceback (most recent call last):
  File "/home/alep/virtualenvs/trader/lib/python3.10/site-packages/lumibot/strategies/strategy_executor.py", line 822, in run
    self._run_trading_session()
  File "/home/alep/virtualenvs/trader/lib/python3.10/site-packages/lumibot/strategies/strategy_executor.py", line 773, in _run_trading_session
    self._on_trading_iteration()
  File "/home/alep/virtualenvs/trader/lib/python3.10/site-packages/lumibot/strategies/strategy_executor.py", line 286, in func_output
    result = func_input(self, *args, **kwargs)
  File "/home/alep/virtualenvs/trader/lib/python3.10/site-packages/lumibot/strategies/strategy_executor.py", line 310, in func_output
    result = func_input(self, *args, **kwargs)
  File "/home/alep/virtualenvs/trader/lib/python3.10/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
  File "/home/alep/virtualenvs/trader/lib/python3.10/site-packages/lumibot/strategies/strategy_executor.py", line 388, in _on_trading_iteration
    on_trading_iteration()
  File "/home/alep/virtualenvs/trader/lib/python3.10/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "/home/alep/virtualenvs/trader/lib/python3.10/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "/home/alep/trading_bot/tradingbot.py", line 27, in on_trading_iteration
    order = self.create_order(
TypeError: Strategy.create_order() got an unexpected keyword argument 'order_type'

2024-04-04 14:46:41,658: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-04-04 14:46:41,659: backtest_stats: INFO: Backtest took 0:00:01.349959 for a speed of 0.000
2024-04-04 14:46:41,659: root: WARNING: Cannot plot returns because the strategy returns are missing
2024-04-04 14:46:41,713: root: WARNING: Cannot create a tearsheet because the strategy returns are missing
